version: '3'

services:
  cnd:
    image: 'cnd:1.0'
    ports:
      - "80:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cnd
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=test

  mysql:
    image: "mysql:8.1.0"
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=cnd

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

